spring:

  profiles: dev

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookerdb
    username: booker
    password: Booker123?%


  jpa:
    hibernate:
      connection:
        charset: utf8
        useUnicode: true
      ddl-auto: create
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
